CONFIG_ZMK_KEYBOARD_NAME="Redragon K552"

# ZMK Studio Settings
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Hardware Safety Overrides
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_EXT_POWER=n

# Spoof the USB VID and PID to bypass corrupted Windows registry caches
CONFIG_USB_DEVICE_VID=0x1234
CONFIG_USB_DEVICE_PID=0x5678
